// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_p2xsCmxShhgJ8XMFkVkXWfvG2r99s50',
    appId: '1:619287801405:web:1854b6f762e7c45f914454',
    messagingSenderId: '619287801405',
    projectId: 'ingredients-app-429412',
    authDomain: 'ingredients-app-429412.firebaseapp.com',
    storageBucket: 'ingredients-app-429412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7hjKR_FPZF-yT31f1tIxGUeGROrpJP4',
    appId: '1:619287801405:android:3a3c303c188f1af0914454',
    messagingSenderId: '619287801405',
    projectId: 'ingredients-app-429412',
    storageBucket: 'ingredients-app-429412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHG23uY3x3I6SA4MMhNFHFWLkGUEyuC4g',
    appId: '1:619287801405:ios:13ac90b4484f43fc914454',
    messagingSenderId: '619287801405',
    projectId: 'ingredients-app-429412',
    storageBucket: 'ingredients-app-429412.appspot.com',
    iosBundleId: 'com.letscook.ingredientCooker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHG23uY3x3I6SA4MMhNFHFWLkGUEyuC4g',
    appId: '1:619287801405:ios:13ac90b4484f43fc914454',
    messagingSenderId: '619287801405',
    projectId: 'ingredients-app-429412',
    storageBucket: 'ingredients-app-429412.appspot.com',
    iosBundleId: 'com.letscook.ingredientCooker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_p2xsCmxShhgJ8XMFkVkXWfvG2r99s50',
    appId: '1:619287801405:web:e4dcf4a062f5325d914454',
    messagingSenderId: '619287801405',
    projectId: 'ingredients-app-429412',
    authDomain: 'ingredients-app-429412.firebaseapp.com',
    storageBucket: 'ingredients-app-429412.appspot.com',
  );
}
